### ISSUE TITLE
Server returns 500 instead of 400 when querying posts of a non-existant board

### ISSUE THREAD

**Issue by cxcorp** [drop-table-ryhmatyo/tekislauta-server#13]
### Description

When board `ayy` doesn't exist:
#### Request

```
GET localhost:1234/api/boards/ayy/posts/1
```
#### Response

```
Status: 500 Server Error
Body: {"status":"Error","data":"A server error has occurred."}
```
### Fix

Currently `DaoException` doesn't differentiate user errors from server errors. Make a new error class instead for user errors?

**Comment by cxcorp** [comment]
Server stack trace:

```
Exception: fi.tekislauta.data.dao.DaoException: Cannot find board b
    at fi.tekislauta.data.dao.PostDao.findPageTopics(PostDao.java:106)
    at fi.tekislauta.webserver.WebServer.lambda$listen$7(WebServer.java:85)
```
